name: Java CI with Gradle

on:
  push:
    branches: [ version/7.0.x ]
  pull_request:
    branches: [ version/7.0.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Submit dependency snapshot
      if: github.event_name == 'push' && github.event.repository.private == false
      uses: gradle/dependency-submission-action@v1
      with:
        snapshot-file: dependency-graph-reports/java_ci_with_gradle-dependency-submission.json
